### PR TITLE
more CPR logic improvements

### PR DESCRIPTION
**Pull request by wiedehopf**
So this should be a good model for dealing with bad CPRs.

Also make the speed check more reliable by using the correct position_valid.update time when doing global CPR.

And add some stats that were never fully implemented.

### CODE REVIEW

**Comment by wiedehopf** [comment]
Would you prefer pull requests against the dev branch or the master branch?

**Comment by Mictronics** [comment]
dev branch is preferred since it gets combined with all other changes and then on release goes into master.

**Comment by wiedehopf** [comment]
I might have some more CPR stuff which kinda goes on top of what i already submitted.

Maybe i should just make a PR for dev with the commits i already did and then the new stuff on top.
Or would that then be a problem when you merge?

Anyway i'm doing some local testing before i will make another PR :)

**Comment by Mictronics** [comment]
Merging shouldn't be a problem. I can solve conflicts manually in any case.

**Pull request merged**
