### PR TITLE
a couple more networking related changes

### PR DESCRIPTION
**Pull request by wiedehopf**
Let me know how you would like the connect/disconnect messages.
(should they all be behind --debug=n ?)

### CODE REVIEW

**Comment by Mictronics** [comment]
@wiedehopf I would like to see at least reconnect messages. So a quick service status shows when and how often a reconnect occurred.

**Comment by wiedehopf** [comment]
So you want messages for the active connectors, but not for the listen ports?

**Comment by wiedehopf** [comment]
Right now it treats them the same and connection establishment and disconnection is printed.

**Comment by Mictronics** [comment]
I think only active makes sense.

**Comment by wiedehopf** [comment]
Ok i can do that.

**Pull request merged**
